### ISSUE TITLE
View festival artists using Ticketmaster API

### ISSUE THREAD

**Issue by jenineellis** [jmdahle/team3project#19]
As a user, I expect to see a list of artists preforming at specific Lollapalooza festival because I want to be able to select a playlist based on one of the artist performing at the festival.

- I expect to see a list of artists that are playing at the festival after I log into the site
- I expect if the list of artists is updated every time the page refreshes or is redrawn
- I expect to view the artists name
- I expect the artist name to be selectable

**Comment by ghost** [comment]
list filtering is now working; click events need to be attached to list items to populate tabbed table.

**Comment by jenineellis** [comment]
#30
