### ISSUE TITLE
Sync local branch to master

### ISSUE THREAD

**Issue by jmdahle** [jmdahle/team3project#22]
Update your own local branch to sync with the master branch
(if you are actively working on code, you should do this FIRST)
1. Go to your branch `git checkout YOURBRANCH`
2. Sync with master `git pull origin master`

Update your local copy of the master branch
1. Go to master branch `git checkout master`
2. Synch local master with current master `git pull master origin`

If you get a page showing a bunch of strange text referencing some merge request and a snaphot, try typing ":q!" and pressing return (you may have gotten a response text file that opened in the default editor... I can explain at class.

We will check in with TAs and Phil to make sure we are going about this correctly.
MOST IMPORTANT: make sure you are in your LOCAL BRANCH before coding.  DO NOT code in the master branch.

**Comment by monuma18** [comment]
Done!
