### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by jmdahle** [jmdahle/team3project#24]
SYNC TO MASTER BEFORE BEGINNING (if possible)
1. Replace user login with a "LOGIN" button for Google (Firebase authentication)
2. Replace Spotify login with a "LOGIN" button for Spotify (Spotify API authentication)
3. Remove date selectors and replace with a search box (for searching band list)

You may add & commit your changes, but do NOT make a pull request.  We can use this together to review the pull request and approval process (perhaps with TA guidance)

**Comment by ghost** [comment]
still have to replace the user login stuff; added "tabs" for display info from spotify and social media thingies... need to closely investigate the bootstrap styles so that we can recolor the tab.

**Comment by ghost** [comment]
more specifically, re: tabs
the blue text isn't legible. i want white text and red tab on hover; tab and field below should have a black background=rgb(0,0,0). tab should be opaque; background of field should be rgba(0, 0, 0, 0.8);

**Comment by ghost** [comment]
fixed the blue text; still not thrilled with styling on tabs, but brain is mushy. looking for a way to add a white border to individual tab, but can't figure it out yet and don't want to mess with tags while js is being connected.

**Comment by ghost** [comment]
redeveloped product logo so that it's more horizontal and takes less real estate. still trying to figure out the tab situation. please attach js/API/ajax stuff so i can do finishing style work.
