### ISSUE TITLE
Ticketmaster API

### ISSUE THREAD

**Issue by jmdahle** [jmdahle/team3project#25]
1. Review TM API call and data model from test-tm.html and tm.js.
2. Identify useful data points in the JSON data model (and document them by their "dot notation" location in the data model.  These can include data points that may be v2/ future development.
3. Try to hook up API call, loop through JSON data to dynamically create a list in the appropriate index.html element.  Recommend creating a new .js file for this purpose and adding a <script> tag to the html to include it.

**Comment by jenineellis** [comment]
added functionality with #30

**Comment by jenineellis** [comment]
#30
