### ISSUE TITLE
Display TM social icons

### ISSUE THREAD

**Issue by jenineellis** [jmdahle/team3project#37]
As a user, I expect to see some social media options related to the artists.

- I expect to see a link for 3 social media options when an artist is selected from the list.
- I expect to see this icons show in the box related to the artist

**Comment by jmdahle** [comment]
* pass urls to get artist function in spot.js
* add urls to page within spot.js (dynamically)

**Comment by jenineellis** [comment]
Closing as won't do. Part of V2
