### ISSUE TITLE
Review/update headings on spotify "panels"

### ISSUE THREAD

**Issue by jmdahle** [jmdahle/team3project#44]
The image and text may need the service of a graphic professional.

**Comment by jmdahle** [comment]
Remove "Playlist" and "Top Tracks" from the heading (dynamically created in spot.js)

**Comment by ghost** [comment]
> The image and text may need the service of a graphic professional.

which file am i looking at?

i'm starting to delete my extra test files... let's get this repo into shape.

**Comment by ghost** [comment]
2 of 3 fixed.

**Comment by ghost** [comment]
fixed with john reworking the js to add a row & class + <br>
